version: '3'

services:
  backend:
    platform: linux/amd64
    image: clairedochez959/backend:latest
    env_file: .env.dev
    depends_on:
      db:
        condition: service_healthy

  frontend:
<<<<<<< HEAD
    image: clairedochez959/frontend
    env_file:
      - .env.dev
    ports:
      - 3000:3000
    volumes:
      - web-client-build:/app/.next
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: atypicar
      POSTGRES_PASSWORD: password
      POSTGRES_DB: atypicardb
      PGDATA: customDataFolder
=======
    platform: linux/amd64
    image: clairedochez959/frontend:latest
    env_file: .env.dev

  db:
    image: postgres
    restart: always
    env_file: .env.db
>>>>>>> 4021cee3f31f20c5b203be9c16595749d4408640
    volumes:
      - ./dbData:/var/lib/postgresql/data/customDataFolder
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d atypicardb -U atypicar" ]
      interval: 5s
      timeout: 5s
      retries: 10

  nginx:
    image: nginx:1.21.3
    platform: linux/amd64
    depends_on:
      - backend
      - frontend
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx
volumes:
  web-client-build:
