version: '3'

services:
  backend:
    platform: linux/amd64
    image: clairedochez959/backend:latest
    env_file: .env.dev
    depends_on:
      db:
        condition: service_healthy

  frontend:
    platform: linux/amd64
    image: clairedochez959/frontend:latest
    env_file: .env.dev

  images:
    platform: linux/amd64
    image: clairedochez959/images:latest

  db:
    image: postgres
    restart: always
    env_file: .env.db
    volumes:
      - ./dbData:/var/lib/postgresql/data/customDataFolder
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d atypicardb -U atypicar" ]
      interval: 5s
      timeout: 5s
      retries: 10

  nginx:
    image: nginx:1.21.3
    platform: linux/amd64
    depends_on:
      - backend
      - frontend
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx

  redis:
    image: redis
  redis-commander:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=redis
    ports:
      - "8081:8081"