version: '3'

services:
  backend:
    image: clairedochez959/backend
    env_file:
      - .env.dev
    ports:
      - 4000:3001
  frontend:
    image: clairedochez959/frontend
    env_file:
      - .env.dev
    ports:
      - 3000:3000
  db:
    image: postgres
    restart: always
    env_file:
      - .env.db
    volumes:
      - ./dbData:/var/lib/postgresql/data/customDataFolder
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d atypicardb -U atypicar" ]
      interval: 5s
      timeout: 5s
      retries: 10
  nginx:
    image: nginx:1.21.3
    depends_on:
      - backend
      - frontend
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
