name : test-ci

on: pull_request

jobs:
  client-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      -name : Goto frontend and run tests
        run: cd frontend && npm install && npm test
