name: test-ci

on:
  pull_request:
    branches: ["staging"]
  workflow_dispatch:

jobs:
  client-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Go to frontend and run 
        run: cd frontend && npm install && npm run dev &
      - name : Goto e2e and run tests
        env:
          BASE_URL: http://localhost:3000 
        run: cd e2e && npm install && npx playwright install &&  npx playwright test 
  docker:
    needs: client-tests
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with: 
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./client
          file: ./client/build.Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/${{ secrets.DOCKER_HUB_CLIENT_IMAGE_NAME }}:latest