name: images-tests-ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  docker:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: "{{defaultContext}}:images"
          file: build.Dockerfile
          tags: ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKER_HUB_UPLOADIMAGES_IMAGE_NAME}}:latest