name: server-dev

on:
  pull_request:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  server-tests:
    runs-on: ubuntu-latest
    container: node:lts-alpine
    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Goto backend and run tests
        env:
          BASE_URL: http://localhost:3001
        run: cd backend && npm install && npm test